server:
  port: 30000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 101.132.250.127:8848
  application:
    name: gulimall-third-party
#mybatis-plus:
#  mapper-locations: classpath*:/mapper/**/*.xml
#  global-config:
#    db-config:
#      id-type: auto
#      #      logic-delete-field: showStatus # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
#      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
#      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
#logging:
#  level:
#    com.atguigu.gulimall: debug